purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2680851
  brandStrength: 0.9462046935223043
  lightness: 0
  brandColors:
    - '#CFBF9B'
    - '#1F1C13'
    - '#254746'
    - '#3B7686'
    - '#8A816F'
  rhythmicContrast: 0.6553192
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Kaya Design
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5234042
layout_spectrum: 0.04977636667899787
