name: Kaya Design
favicon: null
layout_spectrum: 0.049776366678997874
typography_spectrum: 0.5265778517350554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9462046935223043
  lightness: 0.013904772233217955
  saturation: 0.2723659004550427
  rhythmicContrast: 0.7308251864742488
purpose: []
